name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable. 
    runs-on: ${{ (matrix.os == 'freebsd' || matrix.os == 'openbsd') && 'ubuntu-latest' || matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, freebsd, openbsd]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: freebsd
            c_compiler: clang
            cpp_compiler: clang++
          - os: openbsd
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: freebsd
            c_compiler: gcc
          - os: freebsd
            c_compiler: cl
          - os: openbsd
            c_compiler: gcc
          - os: openbsd
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (Native)
      if: matrix.os != 'freebsd' && matrix.os != 'openbsd'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build (Native)
      if: matrix.os != 'freebsd' && matrix.os != 'openbsd'
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test (Native)
      if: matrix.os != 'freebsd' && matrix.os != 'openbsd'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Build and Test (FreeBSD)
      if: matrix.os == 'freebsd'
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: pkg install -y cmake
        run: |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build ${{ steps.strings.outputs.build-output-dir }}
          cd ${{ steps.strings.outputs.build-output-dir }} && ctest

    - name: Build and Test (OpenBSD)
      if: matrix.os == 'openbsd'
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: pkg_add cmake
        run: |
          cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build ${{ steps.strings.outputs.build-output-dir }}
          cd ${{ steps.strings.outputs.build-output-dir }} && ctest
